version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: epv-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - epv-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: epv-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    networks:
      - epv-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: epv-frontend
    environment:
      - REACT_APP_API_URL=http://localhost/api
    ports:
      - "3000:3000"
    networks:
      - epv-network
    restart: unless-stopped

networks:
  epv-network:
    driver: bridge 